### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by clifinger** [Adrinalin4ik/Nestjs-Graphql-Tools#31]
**Describe the bug**
I receive: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '::varchar ilike '%Task%'::varchar))' when I use `Like` filter

**To Reproduce**
```ts
@Query(() => [CategoryType], { nullable: 'itemsAndList' })
  @GraphqlFilter()
  async allCategories(
    @Filter(() => CategoryType) filter: Brackets,
    @Paginator() paginator: PaginatorArgs,
  ): Promise<CategoryType[]> {
    const qb = this.categoriesRepository.createQueryBuilder('c').where(filter);
    console.log(filter);
    if (paginator) {
      qb.offset(paginator.page * paginator.per_page).limit(paginator.per_page);
    }
    return qb.getMany();
  }
```

**Comment by clifinger** [comment]
Do you support only pg ?

**Comment by Adrinalin4ik** [comment]
For now, yes. Filters and sorting are stable for pg only. I will change this behavior soon.
