### ISSUE TITLE
Sorting by multiple fields is passed in the wrong order

### ISSUE THREAD

**Issue by EchoCompanyK** [Adrinalin4ik/Nestjs-Graphql-Tools#33]
**Describe the bug**
I pass to GraphQL in the parameter the first sort by name and the second parameter by id - however, regardless of my order in the resolver, it comes first id then name

**To Reproduce**
1 Set variables
{
  "orderBy": 
    {
      "date_start": "ASC",
      "id":"ASC",
    },
}

2. Query
news(order_by: $orderBy) {
      count
      data {
        id
        name
        date_start
      }
    } 

3. Resolver param
@Sorting(() => NewsModel, {}) sorting: SortArgs< NewsModel >,

4. Log
console.log('sorting', sorting);

5. See error
sorting { id: 'ASC', date_start: 'ASC' }

**Expected behavior**
sorting { date_start: 'ASC', id: 'ASC' }

**Screenshots**
![2023-11-20_19-43-44](https://github.com/Adrinalin4ik/Nestjs-Graphql-Tools/assets/72492140/34690875-fa0d-4f1b-86e8-3a9faadb580d)
![2023-11-20_19-35-02 (2)](https://github.com/Adrinalin4ik/Nestjs-Graphql-Tools/assets/72492140/33889be6-6e68-4210-a4d0-23130f215a6b)

**Version:**
  "nestjs-graphql-tools": "^0.8.4",

**Comment by Adrinalin4ik** [comment]
@EchoCompanyK Actually, it's not a problem. When you're using object it doesn't follow the order you passes in query. Instead try to use an array like
orderBy: [
  { startDate: 'ASC },
  { id: 'ASC' },
  ..etc
]
