### ISSUE TITLE
Add genergic type for `LoaderData`.`parent`

### ISSUE THREAD

**Issue by ruscon** [Adrinalin4ik/Nestjs-Graphql-Tools#34]
**Is your feature request related to a problem? Please describe.**
Right now we have `LoaderData`.`parent` as any

```ts
export interface LoaderData<DtoType, IdType> {
  parent: any;
  // ...
}
```

**Describe the solution you'd like**
I propose to add the ability to specify the type without braking changes

```ts
export interface LoaderData<DtoType, IdType, ParentType extends object = any> {
  parent: ParentType;
}
```

**Comment by Adrinalin4ik** [comment]
@ruscon this is sounds good.

**Comment by Adrinalin4ik** [comment]
This feature was publish as part of the version 0.9.1
