### ISSUE TITLE
@FilterField({ exclude: true }) only excludes the last field in the class when multiple fields are decorated

### ISSUE THREAD

**Issue by bnol** [Adrinalin4ik/Nestjs-Graphql-Tools#48]
**Describe the bug**
There seems to be a bug where the `@FilterField({ exclude: true })` decorator in the `nestjs-graphql-tools` package only excludes the last field it is applied to when multiple fields are marked for exclusion. Fields with `@FilterField({ exclude: true })` that are not the last one in the class are not being excluded as expected.

**To Reproduce**

1. Steps to reproduce the behavior:
2. Define a class with multiple fields, decorating them with `@FilterField({ exclude: true })`.
3. Observe on the GraphQL Playground that only the last field with `@FilterField` which is `createdAt` is excluded from the filter.
```
import { Field, ObjectType } from '@nestjs/graphql';
import { FilterField } from 'nestjs-graphql-tools';

@ObjectType()
export class Request {
  @Field()
  requestId: string;

  @Field()
  @FilterField({ exclude: true })
  requestNumber: string;

  @Field()
  @FilterField({ exclude: true })
  title: string;

  @Field()
  @FilterField({ exclude: true })
  description: string;

  @Field()
  status: string;

  @Field()
  @FilterField({ exclude: true }) // Only this field is excluded
  createdAt: string;
}
```

**Expected behavior**
All fields decorated with `@FilterField({ exclude: true })` should be excluded, not just the last one.

**Additional context**
`"nestjs-graphql-tools": "^0.10.1"`
`"@nestjs/core": "^10.0.0"`
`"@nestjs/graphql": "^12.2.0"`
`Node version: v20.17.0`

**Comment by bnol** [comment]
Here's the screenshot:
![image](https://github.com/user-attachments/assets/92cba9c0-53ed-47e9-990b-98b6a7cd1666)

**Comment by Adrinalin4ik** [comment]
Hey @bnol. Thanks for the report. I'll take a look tomorrow and try to find some options.

**Comment by Adrinalin4ik** [comment]
@bnol I cannot reproduce the same behavior.

This is my model

![image](https://github.com/user-attachments/assets/0fe247b3-7bbc-460d-9f6e-42279e967584)

And this is what I have in the playground

![image](https://github.com/user-attachments/assets/e289a831-2005-413e-b0f8-a365864d2f84)

**Comment by Adrinalin4ik** [comment]
@bnol @bobsingor this is the version that fixes it https://github.com/Adrinalin4ik/Nestjs-Graphql-Tools/releases/tag/0.10.2.
Thanks again for the good find.
